version: '3.8'
services:  
  vprodb:
    build:
      context: ./Docker-files/db
      dockerfile: Dockerfile
    image: vprocontainers/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached:alpine
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    build:
      context: ./Docker-files/app
      dockerfile: Dockerfile
    image: vprocontainers/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build:
      context: ./Docker-files/web
      dockerfile: Dockerfile
    image: vprocontainers/vprofileweb
    container_name: vproweb
    ports:
      - "80:80"
volumes: 
  vprodbdata: {}
  vproappdata: {}

  